// src/icons.ts
import { addIcons } from "ionicons";
import {
  searchOutline,
  homeOutline,
  scanOutline,
  cubeOutline,
  eye,
  eyeOff,
  personOutline,
  person,
  lockClosedOutline,
  lockClosed,
  arrowForwardOutline,
  documentTextOutline,
  cardOutline,
  callOutline,
  calendarOutline,
  mailOutline,
  logOutOutline,
  swapHorizontalOutline,
  keyOutline,
  arrowRedoOutline,
  arrowUndoOutline,
  informationCircleOutline,
  locationOutline,
  fileTrayStackedOutline,
  hourglassOutline,
  schoolOutline,
  desktop,
  desktopOutline,
  qrCodeOutline,
  closeCircleOutline,
  lockOpenOutline,
  closeOutline,
  calendarNumberOutline,
  arrowRedo,
  arrowUndo,
  logIn,
  logOut,
} from "ionicons/icons";

addIcons({
  "search-outline": searchOutline,
  "home-outline": homeOutline,
  "scan-outline": scanOutline,
  "cube-outline": cubeOutline,
  person: person,
  eye: eye,
  "eye-off": eyeOff,
  "person-outline": personOutline,
  "lock-closed-outline": lockClosedOutline,
  "lock-closed": lockClosed,
  "arrow-forward-outline": arrowForwardOutline,
  "document-text-outline": documentTextOutline,
  "card-outline": cardOutline,
  "calendar-outline": calendarOutline,
  "call-outline": callOutline,
  "mail-outline": mailOutline,
  "log-out-outline": logOutOutline,
  "swap-horizontal-outline": swapHorizontalOutline,
  "key-outline": keyOutline,
  "arrow-redo-outline": arrowRedoOutline,
  "arrow-undo-outline": arrowUndoOutline,
  "information-circle-outline": informationCircleOutline,
  "location-outline": locationOutline,
  fileTrayStackedOutline: fileTrayStackedOutline,
  "hourglass-outline": hourglassOutline,
  "school-outline": schoolOutline,
  desktop: desktop,
  "desktop-outline": desktopOutline,
  "qr-code-outline": qrCodeOutline,
  "close-circle-outline": closeCircleOutline,
  "lock-open-outline": lockOpenOutline,
  "close-outline": closeOutline,
  "calendar-number-outline": calendarNumberOutline,
  "arrow-redo": arrowRedo,
  "arrow-undo": arrowUndo,
  "log-in": logIn,
  "log-out": logOut,
});
